# This Rakefile has all the right settings to run the tests inside each lab
require 'rspec'
require 'rspec/core/rake_task'

task :default => :spec

desc "run tests for this lab"
RSpec::Core::RakeTask.new do |task|
  task.pattern = "./spec/*_spec.rb"
  task.rspec_opts = ['-f documentation']
  task.verbose = false
end
